name: SkyblockMenu
api: [3.0.0x , 4.0.0]
author: Nomi
version: 1
main: SkyblockMenu\Nomi\Main

commands:
  skyblockmenu:
    description: skyblock menu commands
    permission: skyblockmenu.open.menu  
    default: true
