#HI HEHEBOI 
#You Can Edit Commands Here for Gui
#Add Any Command That You Want To Excute From GUI


#These Are Main Items Commands


#Skill Command
skill: "your command here"

#Collections Command
collections: "your command here"

#Recipes Command
recipes: "your command here"

#Trade Command
trade: "your command here"

#Quest Command
quest: "your command here"

#Events command
event: "your command here"

#Ender Chest Command
ender_chest: "your command here"

#Potions Shop Command
potions_shop: "your command here"

#Pets Command
pets: "your command here"

#Crafting Table Command
crafting_table: "your command here"

#wardrope command
wardrope: "your command here"

#Bank Command
bank: "your command here"

#profile command here
profile: "your command here"

#travel island command
island: "your command here"

#fast travel Command
fast_travel: "your command here"

#island Settings Command
island_settings: "your command here"

#Note This Plugin is Created By Mr Nomi MC And you Are Not Allowed To Change Author Name !!!
